s=open('trend.html').read()
R=[
('</style></head>','</style><style>html,body{width:1080px!important;height:1920px!important}#stage{width:1080px;height:1920px}.arc,.arc2{transform:scale(.8)}</style></head>'),
('.wm2{position:absolute;right:56px;top:46px;','.wm2{position:absolute;left:50%;transform:translateX(-50%);top:70px;'),
('<div class="glass tag" id="tag1">','<div class="glass tag" id="tag1" style="left:50%;top:300px;margin-left:-160px">'),
('<div style="position:absolute;left:0;right:0;top:250px;display:flex;justify-content:center"><div class="gptTile" id="gtile">','<div style="position:absolute;left:0;right:0;top:520px;display:flex;justify-content:center"><div class="gptTile" id="gtile" style="width:200px;height:200px;border-radius:50px">'),
('<div style="position:absolute;left:0;right:0;top:470px" class="head"><div style="font-size:150px" id="h1"><span class="w">ChatGPT</span> <span class="w">just</span> <span class="w">changed.</span></div>\n  <div style="font-size:150px;margin-top:10px">',
 '<div style="position:absolute;left:0;right:0;top:820px" class="head"><div style="font-size:140px;line-height:1.05" id="h1"><span class="w">ChatGPT</span><br><span class="w">just</span> <span class="w">changed.</span></div>\n  <div style="font-size:170px;margin-top:30px">'),
('<div style="position:absolute;left:0;right:0;top:230px;text-align:center">\n    <div class="big" style="font-size:330px">','<div style="position:absolute;left:0;right:0;top:560px;text-align:center">\n    <div class="big" style="font-size:300px">'),
('<div class="head" style="font-size:64px;margin-top:20px;color:rgba(255,255,255,.85)"><span class="w">people</span> <span class="w">use</span> <span class="w">ChatGPT</span> <span class="w grad">every</span> <span class="w grad">week</span></div>',
 '<div class="head" style="font-size:72px;margin-top:40px;color:rgba(255,255,255,.88);line-height:1.15"><span class="w">people</span> <span class="w">use</span> <span class="w">ChatGPT</span><br><span class="w grad">every</span> <span class="w grad">week</span></div>'),
('.bars{position:absolute;left:0;right:0;bottom:0;height:520px;display:flex;align-items:flex-end;gap:14px;padding:0 120px;opacity:.55}','.bars{position:absolute;left:0;right:0;bottom:0;height:640px;display:flex;align-items:flex-end;gap:10px;padding:0 40px;opacity:.55}'),
('.src{position:absolute;left:150px;bottom:150px;','.src{position:absolute;left:0;right:0;text-align:center;bottom:120px;'),
('<div style="position:absolute;left:0;right:0;top:250px;text-align:center" class="head"><div style="font-size:44px;letter-spacing:.4em;','<div style="position:absolute;left:0;right:0;top:640px;text-align:center" class="head"><div style="font-size:40px;letter-spacing:.3em;'),
('<div class="dot3" id="d1" style="left:828px;top:470px"></div><div class="dot3" id="d2" style="left:928px;top:470px"></div><div class="dot3" id="d3" style="left:1028px;top:470px"></div>',
 '<div class="dot3" id="d1" style="left:408px;top:900px"></div><div class="dot3" id="d2" style="left:508px;top:900px"></div><div class="dot3" id="d3" style="left:608px;top:900px"></div>'),
('<div style="position:absolute;left:0;right:0;top:395px;text-align:center"><div class="big grad" style="font-size:250px" id="dots">','<div style="position:absolute;left:0;right:0;top:810px;text-align:center"><div class="big grad" style="font-size:280px" id="dots">'),
('<div style="position:absolute;left:0;right:0;top:700px;text-align:center" class="head"><div style="font-size:46px;color:rgba(255,255,255,.8);font-weight:600" id="dsub"><span class="w">Always-on</span> <span class="w">AI</span> <span class="w">agents</span> <span class="w">in</span> <span class="w">ChatGPT</span></div>',
 '<div style="position:absolute;left:0;right:0;top:1150px;text-align:center" class="head"><div style="font-size:52px;color:rgba(255,255,255,.85);font-weight:600;line-height:1.2" id="dsub"><span class="w">Always-on</span> <span class="w">AI</span> <span class="w">agents</span><br><span class="w">in</span> <span class="w">ChatGPT</span></div>'),
('id="chat" style="left:150px;top:220px;width:700px;height:560px"','id="chat" style="left:70px;top:600px;width:940px;height:600px"'),
('id="work" style="left:1000px;top:220px;width:770px;height:560px"','id="work" style="left:70px;top:600px;width:940px;height:520px"'),
('<div class="glass status" id="off" style="left:150px;top:800px">','<div class="glass status" id="off" style="left:70px;top:1300px">'),
('<div class="clock" id="clk" style="left:430px;top:792px">','<div class="clock" id="clk" style="left:70px;top:1400px;font-size:120px">'),
('<div style="position:absolute;left:0;right:0;top:80px;text-align:center" class="head"><div style="font-size:64px" id="s4t"><span class="w">Handled</span> <span class="w">—</span> <span class="w grad">while</span> <span class="w grad">you</span> <span class="w grad">sleep.</span></div>',
 '<div style="position:absolute;left:0;right:0;top:250px;text-align:center" class="head"><div style="font-size:92px;line-height:1.1" id="s4t"><span class="w">Handled</span><br><span class="w grad">while</span> <span class="w grad">you</span> <span class="w grad">sleep.</span></div>'),
("tl.to('#work',{x:-220,duration:.6,ease:'power3.inOut'},12.15);",""),
(".msg{margin:22px 28px;padding:18px 24px;border-radius:20px;font-size:24px;line-height:1.35;max-width:520px}",".msg{margin:26px 30px;padding:22px 28px;border-radius:22px;font-size:32px;line-height:1.35;max-width:720px}"),
(".task{display:flex;align-items:center;gap:18px;padding:22px 26px;margin:14px 22px;border-radius:20px;background:rgba(255,255,255,.06);font-size:26px;font-weight:500}",".task{display:flex;align-items:center;gap:20px;padding:30px 30px;margin:20px 26px;border-radius:22px;background:rgba(255,255,255,.06);font-size:34px;font-weight:500}"),
(".winbar{height:64px;",".winbar{height:80px;font-size:30px!important;"),
('<div style="position:absolute;left:0;right:0;top:120px;text-align:center" class="head"><div style="font-size:72px" id="s5a"><span class="w">Its</span> <span class="w">own</span> <span class="w grad">cloud</span> <span class="w grad">computer</span></div>',
 '<div style="position:absolute;left:0;right:0;top:260px;text-align:center" class="head"><div style="font-size:96px;line-height:1.08" id="s5a"><span class="w">Its</span> <span class="w">own</span><br><span class="w grad">cloud</span> <span class="w grad">computer</span></div>'),
('<div style="position:absolute;left:0;right:0;top:860px;text-align:center" class="head"><div style="font-size:72px" id="s5b">','<div style="position:absolute;left:0;right:0;top:1480px;text-align:center" class="head"><div style="font-size:92px;line-height:1.1" id="s5b">'),
('<span class="w grad">+</span> <span class="w">connected</span> <span class="w">apps</span>','<span class="w grad">+</span><br><span class="w">connected</span> <span class="w">apps</span>'),
('const pos=(a)=>({x:960+Math.cos(a)*R*1.35,y:530+Math.sin(a)*R*.78});','const pos=(a)=>({x:540+Math.cos(a)*R*1.25,y:1000+Math.sin(a)*R*1.05});'),
('.core{position:absolute;left:50%;top:50%;','.core{position:absolute;left:50%;top:1000px;'),
('<div style="position:absolute;left:150px;top:190px" id="s6l">','<div style="position:absolute;left:80px;top:300px" id="s6l">'),
('<div class="head" style="font-size:96px;text-align:left;margin-top:40px">','<div class="head" style="font-size:110px;text-align:left;margin-top:40px">'),
('id="ide" style="left:1010px;top:200px;width:780px;height:600px"','id="ide" style="left:60px;top:960px;width:960px;height:680px"'),
("{opacity:1,x:0,rotateY:-6,duration:.8,ease:'expo.out'},21.2)","{opacity:1,x:0,rotateY:0,duration:.8,ease:'expo.out'},21.2)"),
(".code{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:27px;",".code{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:31px;"),
('<div style="position:absolute;left:150px;top:220px" id="s7l" class="head">','<div style="position:absolute;left:80px;top:260px" id="s7l" class="head">'),
('id="vc" style="left:1130px;top:200px;width:640px;height:520px;padding:50px 54px"','id="vc" style="left:160px;top:960px;width:760px;height:540px;padding:50px 56px"'),
("style=\"left:${40+i*466}px\"","style=\"left:${40+(i%2)*520}px;bottom:${i<2?140:40}px;width:480px\""),
]
for a,b in R:
  assert a in s,a[:70]; s=s.replace(a,b)
open('trend_v.html','w').write(s)
